# Generated by Django 4.0.5 on 2022-06-27 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Master',
            fields=[
                ('primary_key', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30)),
                ('investment_name', models.CharField(max_length=30)),
                ('prepare_by', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('firm_address', models.CharField(max_length=30)),
                ('brief_project', models.CharField(max_length=30)),
            ],
        ),
    ]
